version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: validator
    main: ./cmd/validator/
    binary: validator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - formats: [tar.gz]
    name_template: >-
      starknet-staking-v2_{{ .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

kos:
  - id: validator-image
    build: validator
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64
    repositories:
      - docker.io/nethermind/starknet-staking-v2
    tags:
      - "{{ .Tag }}"
      - latest

release:
  github:
    owner: NethermindEth
    name: starknet-staking-v2
  prerelease: auto
  draft: true
  footer: |-
    ## Docker Images

    - `nethermind/starknet-staking-v2:{{ .Tag }}`
    - `nethermind/starknet-staking-v2:latest`