name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-image-build
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  ARTIFACTORY_DOCKER_REPO: nubia-oci-local-dev
  DOCKER_IMAGE_NAME: starknet-staking-v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define image tag
        id: set_tag
        run: |
          export DOCKER_IMAGE_TAG=$(git describe --tags)
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to registry
        run: docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Build & push Docker images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.ARTIFACTORY_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.ARTIFACTORY_DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}